[package]
name = "logik_lib"
version = "0.1.0"
edition = "2021"

[target.aarch64-apple-darwin]
linker = "rust-lld"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab_tree = "0.3.2"
derive_more = "0.99.17"
